# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Bootstrap project
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sumittuladhar.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

#allow future post date to show
future: true

#http://damonbauer.me/organizing-jekyll-pages/
include: ["_pages"]
permalink: /go/:title/

# Build settings
markdown: kramdown
highlighter: rouge

sub-navigation:
- title: Home
  url: '/'
- title: Readme
  url: 'readme.html'
- title: About
  url: 'about.html'

#permalink: "/blog/:categories/:title.html"
#paginate_path: "/blog/page:num"
#paginate: 2

gems:
  - jekyll-sitemap

sass:
  # loading path from site root
  # default to _sass
  sass_dir: lib/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
